import { Platform, StyleSheet } from 'react-native';

const border = '#1f2d46';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#07111f',
  },
  avoidingView: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#07111f',
    paddingHorizontal: 16,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 16,
  },
  card: {
    backgroundColor: '#0f1a2b',
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: border,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.22,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
      },
      android: {
        elevation: 3,
      },
      web: {
        boxShadow: '0 12px 30px rgba(0, 0, 0, 0.22)',
      },
    }),
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  calcBadge: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#22c55e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kicker: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  title: {
    color: '#eef2ff',
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 32,
  },
  subtitle: {
    color: '#b6c2d9',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
    marginBottom: 18,
  },
  input: {
    backgroundColor: '#07111f',
    borderWidth: 1,
    borderColor: border,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 14 : 12,
    color: '#eef2ff',
    fontSize: 16,
    marginBottom: 12,
  },
  toolRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  toolButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#17253b',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    borderWidth: 1,
    borderColor: border,
  },
  toolButtonSoft: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  toolButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  toolButtonText: {
    color: '#eef2ff',
    fontSize: 13,
    fontWeight: '800',
  },
  toolButtonTextDark: {
    color: '#07111f',
    fontSize: 13,
    fontWeight: '900',
  },
  buttonsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  opButton: {
    width: '48%',
    minHeight: 88,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: border,
  },
  opButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  sumButton: {
    backgroundColor: '#1e293b',
  },
  restButton: {
    backgroundColor: '#16263f',
  },
  mulButton: {
    backgroundColor: '#163528',
  },
  divButton: {
    backgroundColor: '#3b1d1d',
  },
  opSymbol: {
    color: '#eef2ff',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 28,
  },
  opLabel: {
    color: '#b6c2d9',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
    textAlign: 'center',
  },
  resultBox: {
    marginTop: 8,
    backgroundColor: '#07111f',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: border,
  },
  resultLabel: {
    color: '#22c55e',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  result: {
    color: '#eef2ff',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
  },
  historyBox: {
    marginTop: 14,
    backgroundColor: '#12263f',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#2c4a74',
  },
  historyTitle: {
    color: '#dbeafe',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 10,
  },
  historyEmpty: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
  },
  historyItem: {
    backgroundColor: '#07111f',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: border,
  },
  historyItemText: {
    color: '#eef2ff',
    fontSize: 13,
    fontWeight: '700',
  },
});
