import { Platform, StyleSheet } from 'react-native';

const border = '#1f2d46';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#07111f',
  },
  listContent: {
    padding: 16,
    paddingBottom: 28,
  },
  heroCard: {
    backgroundColor: '#0f1a2b',
    borderRadius: 28,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: border,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    gap: 12,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#22c55e',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  pillText: {
    color: '#06111f',
    fontWeight: '900',
    fontSize: 12,
  },
  pillSoft: {
    backgroundColor: '#17253b',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: border,
  },
  pillSoftText: {
    color: '#e2e8f0',
    fontWeight: '800',
    fontSize: 12,
  },
  kicker: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  title: {
    color: '#eef2ff',
    fontSize: 30,
    lineHeight: 35,
    fontWeight: '900',
    marginBottom: 10,
  },
  subtitle: {
    color: '#b6c2d9',
    fontSize: 15,
    lineHeight: 22,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#13233d',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: border,
  },
  statValue: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '700',
  },
  card: {
    backgroundColor: '#0f1a2b',
    borderRadius: 24,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: border,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.22,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
      },
      android: {
        elevation: 3,
      },
      web: {
        boxShadow: '0 12px 30px rgba(0, 0, 0, 0.22)',
      },
    }),
  },
  cardAccent: {
    backgroundColor: '#12263f',
    borderRadius: 24,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#2c4a74',
  },
  sectionTitle: {
    color: '#eef2ff',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
  },
  sectionTitleAccent: {
    color: '#dbeafe',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
  },
  helperText: {
    color: '#b6c2d9',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  helperTextAccent: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  actionsGrid: {
    gap: 12,
  },
  actionButton: {
    backgroundColor: '#17253b',
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: border,
  },
  actionButtonPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.96,
  },
  actionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#22c55e',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  actionButtonText: {
    color: '#eef2ff',
    fontSize: 16,
    fontWeight: '900',
  },
  actionButtonNote: {
    color: '#94a3b8',
    fontSize: 13,
    marginTop: 3,
  },
  messageChip: {
    marginTop: 14,
    backgroundColor: '#07111f',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: border,
  },
  messageLabel: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  message: {
    color: '#eef2ff',
    fontSize: 15,
    fontWeight: '700',
  },
  lastAction: {
    marginTop: 10,
    color: '#94a3b8',
    fontSize: 13,
  },
  primaryButton: {
    backgroundColor: '#22c55e',
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
  },
  primaryButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  primaryButtonText: {
    color: '#06111f',
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    backgroundColor: '#e5e7eb',
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  secondaryButtonPressed: {
    opacity: 0.85,
  },
  secondaryButtonText: {
    color: '#111827',
    fontWeight: '800',
  },
  confirmButton: {
    backgroundColor: '#22c55e',
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  confirmButtonPressed: {
    opacity: 0.9,
  },
  confirmButtonText: {
    color: '#06111f',
    fontWeight: '900',
  },
  listItem: {
    backgroundColor: '#0f1a2b',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: border,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  listItemBadge: {
    backgroundColor: '#17253b',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: border,
  },
  listItemBadgeText: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '900',
  },
  listItemTitle: {
    color: '#eef2ff',
    fontSize: 16,
    fontWeight: '800',
  },
  listItemSubtitle: {
    color: '#94a3b8',
    fontSize: 13,
    marginTop: 4,
  },
  footer: {
    alignItems: 'center',
    paddingVertical: 18,
  },
  footerText: {
    color: '#94a3b8',
    fontSize: 13,
    marginTop: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(3, 7, 18, 0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#0f1a2b',
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: border,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  modalIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#22c55e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    color: '#eef2ff',
    fontSize: 20,
    fontWeight: '900',
  },
  modalSubtitle: {
    color: '#94a3b8',
    fontSize: 13,
    marginTop: 2,
  },
  modalText: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
  },
  modalActions: {
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
});
