import { Platform, StyleSheet } from 'react-native';

const border = '#1f2d46';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#07111f',
    padding: 16,
  },
  card: {
    backgroundColor: '#0f1a2b',
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: border,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.22,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
      },
      android: {
        elevation: 3,
      },
      web: {
        boxShadow: '0 12px 30px rgba(0, 0, 0, 0.22)',
      },
    }),
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  heroIcon: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: '#38bdf8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kicker: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  title: {
    color: '#eef2ff',
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 32,
  },
  subtitle: {
    color: '#b6c2d9',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
    marginBottom: 16,
  },
  infoGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  infoCard: {
    flex: 1,
    backgroundColor: '#12263f',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: '#2c4a74',
  },
  infoLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  infoValue: {
    color: '#eef2ff',
    fontSize: 15,
    fontWeight: '900',
  },
  label: {
    color: '#eef2ff',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 10,
  },
  pickerWrapper: {
    borderWidth: 1,
    borderColor: border,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#07111f',
  },
  picker: {
    width: '100%',
    color: '#eef2ff',
  },
  dropdownTrigger: {
    minHeight: 64,
    borderWidth: 1,
    borderColor: '#2c4a74',
    borderRadius: 18,
    backgroundColor: '#12263f',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dropdownTriggerPressed: {
    opacity: 0.88,
  },
  dropdownTriggerText: {
    color: '#eef2ff',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 4,
  },
  dropdownTriggerSubtext: {
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 16,
    maxWidth: 250,
  },
  dropdownModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(3, 7, 18, 0.72)',
    justifyContent: 'center',
    padding: 18,
  },
  dropdownModalCard: {
    backgroundColor: '#0f1a2b',
    borderRadius: 26,
    padding: 14,
    borderWidth: 1,
    borderColor: border,
  },
  dropdownModalTitle: {
    color: '#eef2ff',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 10,
  },
  dropdownOption: {
    minHeight: 60,
    borderRadius: 16,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginVertical: 4,
    backgroundColor: '#07111f',
    borderWidth: 1,
    borderColor: border,
  },
  dropdownOptionPressed: {
    opacity: 0.92,
  },
  dropdownOptionSelected: {
    backgroundColor: '#12263f',
    borderColor: '#22c55e',
  },
  optionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  optionIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#17253b',
  },
  optionIconSelected: {
    backgroundColor: '#22c55e',
  },
  dropdownOptionText: {
    color: '#eef2ff',
    fontSize: 15,
    fontWeight: '800',
  },
  dropdownOptionTextSelected: {
    color: '#22c55e',
  },
  dropdownOptionSubtext: {
    color: '#94a3b8',
    fontSize: 12,
    marginTop: 2,
    lineHeight: 16,
  },
  dropdownDoneButton: {
    marginTop: 10,
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: '#22c55e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownDoneButtonPressed: {
    opacity: 0.9,
  },
  dropdownDoneButtonText: {
    color: '#07111f',
    fontSize: 15,
    fontWeight: '900',
  },
  selectionBox: {
    marginTop: 18,
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#12263f',
    borderWidth: 1,
    borderColor: '#2c4a74',
  },
  selectionLabel: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  selectionValue: {
    color: '#eef2ff',
    fontSize: 20,
    fontWeight: '900',
  },
  selectionDesc: {
    color: '#b6c2d9',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  selectionMetaRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  metaChip: {
    backgroundColor: '#07111f',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: border,
  },
  metaChipText: {
    color: '#dbeafe',
    fontSize: 12,
    fontWeight: '800',
  },
});
